// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         text: "foo",
 *         language: "ar-kw",
 *         voice_id: 1
 *     }
 */
export interface CreateStreamTtsRequestPayload {
    text: string;
    language: CreateStreamTtsRequestPayload.Language;
    voice_id: number;
    speech_model?: CreateStreamTtsRequestPayload.SpeechModel;
    user_instructions?: string | null;
    enhance_named_entities_pronunciation?: boolean;
    output_configuration?: CambApi.StreamTtsOutputConfiguration;
    voice_settings?: CambApi.StreamTtsVoiceSettings;
    inference_options?: CambApi.StreamTtsInferenceOptions;
}

export namespace CreateStreamTtsRequestPayload {
    export const Language = {
        ArKw: "ar-kw",
        DeCh: "de-ch",
        KoKr: "ko-kr",
        ThTh: "th-th",
        MlIn: "ml-in",
        PtPt: "pt-pt",
        KnIn: "kn-in",
        FiFi: "fi-fi",
        EsMx: "es-mx",
        FrCa: "fr-ca",
        CsCz: "cs-cz",
        PtBr: "pt-br",
        HiIn: "hi-in",
        ArSy: "ar-sy",
        EsUs: "es-us",
        BnBd: "bn-bd",
        JaJp: "ja-jp",
        MrIn: "mr-in",
        ArMa: "ar-ma",
        EsEs: "es-es",
        EnUs: "en-us",
        ZhCn: "zh-cn",
        ElGr: "el-gr",
        PlPl: "pl-pl",
        ArOm: "ar-om",
        FrCh: "fr-ch",
        EnUk: "en-uk",
        EnAu: "en-au",
        ArJo: "ar-jo",
        ArAe: "ar-ae",
        TrTr: "tr-tr",
        ArLy: "ar-ly",
        RuRu: "ru-ru",
        EnIn: "en-in",
        ArYe: "ar-ye",
        ArEg: "ar-eg",
        FrBe: "fr-be",
        TaIn: "ta-in",
        ZhTw: "zh-tw",
        ViVn: "vi-vn",
        BnIn: "bn-in",
        ArSa: "ar-sa",
        DeAt: "de-at",
        PaIn: "pa-in",
        ItIt: "it-it",
        NlNl: "nl-nl",
        ArBh: "ar-bh",
        FrFr: "fr-fr",
        ArQa: "ar-qa",
        UkUa: "uk-ua",
        ArTn: "ar-tn",
        DeDe: "de-de",
        ArXa: "ar-xa",
        ArLb: "ar-lb",
        ZhHk: "zh-hk",
        RoRo: "ro-ro",
        AsIn: "as-in",
        ArIq: "ar-iq",
        NlBe: "nl-be",
        TeIn: "te-in",
        IdId: "id-id",
        ArDz: "ar-dz",
    } as const;
    export type Language = (typeof Language)[keyof typeof Language];
    export const SpeechModel = {
        Auto: "auto",
        Mars8: "mars-8",
        Mars8Flash: "mars-8-flash",
        Mars8Instruct: "mars-8-instruct",
        Mars7: "mars-7",
        Mars6: "mars-6",
        MarsPro: "mars-pro",
        MarsFlash: "mars-flash",
        MarsInstruct: "mars-instruct",
    } as const;
    export type SpeechModel = (typeof SpeechModel)[keyof typeof SpeechModel];
}
